### ISSUE TITLE
data/sinc0.vxl is not used for about 3 years and still takes 2MB in repo

### ISSUE THREAD

**Issue by noway421** [NateShoffner/PySnip#11]
`data/sinc0.vxl` used only in one file: `experimental/test_world.py`. Even presence of this file is questionable, because this file was used only in initial development of pyspades and has not been fired up by anyone for at least several years. Not to mention it is not working (no such module as pyspades.load anymore). 

As all map files, and `GeoLiteCity.dat`, it could be separated in some detached file repository. I propose to put it somewhere on buildandshoot (`http://buildandshoot.com/extra-files/sinc0.vxl`, something like that) and provide link in `experimental/test_world.py` for future archaeologists.

Motivation: after that zipped size of master branch would drop from 1126K to 318K which is good for faster deploy (git clone --depth 1).

**Comment by NateShoffner** [comment]
Removed unused experimental files in https://github.com/NateShoffner/PySnip/commit/24cc280ded114d281dd60148a553b5f034656f0c. No use in really retaining them elsewhere.
