### ISSUE TITLE
py2exe build script probably should include pillow and jinja2.

### ISSUE THREAD

**Issue by noway421** [NateShoffner/PySnip#13]
Jinja2 is used for statusserver and pillow is needed to render map screenshot. Don't have windows machine, are these functions working in windows build?

**Comment by noway421** [comment]
Also, pycrypto and pyasn1 are needed for ssh, but only pyasn1 is present.

**Comment by NateShoffner** [comment]
Added jinja2 and pillow to the build script in https://github.com/NateShoffner/PySnip/commit/97c7dbe16a33f1a73cc73f2f13b11cd84e4b1124. You sure about pycrypto? Don't see any usage of it and SSH seems to work fine without it.

**Comment by noway421** [comment]
Awesome! Well, on linux you have to install pycrypto for using pysnip ssh ability, so i just thought it same on windows. Apparently, on windows this feature already built-in in twisted on compile time (twisted handles ssh after all).
If ssh is working on windows, then i'm closing.
